[package]
name = "MiiCut"
version = "0.1.0"
edition = "2021"

[dependencies]
# kurbo = { git = "https://github.com/linebender/kurbo" }
ttf-parser = "0.25.1"
kurbo = "0.11.1"
geo = "0.29.3"
approx = "0.5.1"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.24"
js-sys = "0.3.70"

[dependencies.web-sys]
version = "0.3.64"
features = [
    "CanvasRenderingContext2d",
    "CssStyleDeclaration",
    "Document",
    "Element",
    "FontFaceSet",
    "EventTarget",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlInputElement",
    "MouseEvent",
    "KeyEvent",
    "File",
    "FileList",
    "FileReader",
    "Window",
    "console",
    "DomRect",
    "Path2d",
    "WheelEvent",
    "KeyboardEvent",
    "Text",
]
