[package]
name = "MiiCut"
version = "0.1.0"
edition = "2021"

[dependencies]
# kurbo = { git = "https://github.com/linebender/kurbo" }
ttf-parser = "0.25.1"
svg = "0.18.0"
kurbo = "0.11.2"
geo = "0.30.0"
approx = "0.5.1"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4"
js-sys = "0.3.70"
strum = "0.24"
strum_macros = "0.24"
urlencoding = "2"

[dependencies.web-sys]
version = "0.3.64"
features = [
    "CanvasRenderingContext2d",
    "CssStyleDeclaration",
    "Document",
    "Element",
    "FontFaceSet",
    "EventTarget",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlInputElement",
    "MouseEvent",
    "KeyEvent",
    "File",
    "FileList",
    "FileReader",
    "Window",
    "console",
    "DomRect",
    "Path2d",
    "WheelEvent",
    "KeyboardEvent",
    "Text",
    "Performance",
    "WebSocket",
    "MessageEvent",
    "Blob",
    "CloseEvent",
    "Event",
    "BinaryType",
    "Response",
    "DomTokenList",
]
